### ISSUE TITLE
UI hides text

### ISSUE THREAD

**Issue by zwolfe21** [theycallmemac/pipboy-ui#1] opened 2017-11-14 23:48 UTC
First: Love this idea!! Nerding out on it!

Now the bad stuff, 

Some text and boxes are hidden when using pipboy-ui and pipboy-syntax. See below. Also, the third image, I was curious if the pipboy terminal background was supposed to stretch over the screen window instead of looking like that. 

![screenshot from 2017-11-14 18-45-32](https://user-images.githubusercontent.com/24982704/32811143-35fd86cc-c96c-11e7-94d2-00adbfdeace0.png)
![screenshot from 2017-11-14 18-45-42](https://user-images.githubusercontent.com/24982704/32811144-3890630a-c96c-11e7-821c-8fe807e0b283.png)

![screenshot from 2017-11-14 18-46-02](https://user-images.githubusercontent.com/24982704/32811145-3ad4ee2e-c96c-11e7-8184-ec106effa4dc.png)

**Comment by theycallmemac** [comment] 2017-11-14 23:52
Yeah I put this together quite quick with very little follow up, although it was intended!  If you'd like to fix it I'd love the help!

The pip-boy image should most definitely stretch over instead of looking like that. I feel like I will have some time in a week or two to proberly fix this (it's been on a to do list for a while!), but again, if you have fixes, feel free to make a PR! :)

**Comment by zwolfe21** [comment] 2017-11-15 00:43
I tweaked some things, (had to learn how ha!) but this is what I did. I'll add my ui-variables file as well. I was able to fix the core color issue but I tweaked some of the greens in other areas. But its that first one, @pane-item-background-color that is the issue I mentioned above. 

Just for clarification, [ORIGINAL VALUE] -> [NEW VALUE]

@pane-item-background-color: #0c833d -> #052308;
@app-background-color:        #0c833d -> #052308;
@input-background-color: #0c833d -> #1c4221;
@input-border-color:     #1cfa80 -> #0c833d;
@base-background-color:  #213721 -> #052308;
@tab-background-color-active: lighten(@tab-bar-background-color, 10% -> 5%);
@background-color-selected:  #0c833d -> #3b5c3b;
@tool-panel-background-color: #063315 -> #001100;


[ui-variables.zip](https://github.com/theycallmemac/pipboy-ui/files/1473002/ui-variables.zip)

**Comment by zwolfe21** [comment] 2017-11-15 00:44
Oh, Here are SS of what the color chages did if your interested in seeing them 
![screenshot from 2017-11-14 19-44-01](https://user-images.githubusercontent.com/24982704/32812675-3be3c71a-c974-11e7-87d6-2bcaa96a4937.png)
![screenshot from 2017-11-14 19-43-58](https://user-images.githubusercontent.com/24982704/32812677-3d4d60ca-c974-11e7-839a-c00e158ba873.png)

**Comment by theycallmemac** [comment] 2017-11-15 00:49
That looks great man thanks :) are you sending a PR or do you want me to enter them?

**Comment by zwolfe21** [comment] 2017-11-15 00:52
I frankly have no idea how to use github TBH. I should probably learn. Meaning you might as well enter them I suppose.

Also, scaling that image to the window is fixed by setting 

  background-size: 1010px 800px; to background-size: cover; 

in pipboy-syntax -> styles -> base.less


![screenshot from 2017-11-14 19-51-00](https://user-images.githubusercontent.com/24982704/32812850-2829cdd6-c975-11e7-9100-935894040944.png)

**Comment by theycallmemac** [comment] 2017-11-15 00:54
It's not too hard, time and you'll get there!

I'll enter these values and push the new release and close this issue afterwards. Thanks!

**Comment by theycallmemac** [comment] 2017-11-15 01:10
That should be fixed now, I've made changes to both and they have been published. :)

**Closed as completed by theycallmemac** 2017-11-15 01:10 UTC
